version: '3.8'

services:
  # NestJS Application
  app:
    container_name: invoiceapp
    image: invoiceapp:latest
    hostname: invoiceapp
    ports:
      - "3000:3000"
    volumes:
      - ./invoiceapp:/app
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:root123@mongodb:27017/invoiceapp
    depends_on:
      - mongodb
    command: npm run start:dev

  # MongoDB Database
  mongodb:
    container_name: mongodb
    image: mongo:latest
    hostname: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
      - MONGO_INITDB_DATABASE=invoiceapp

  # MongoDB Express
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root123
    depends_on:
      - mongodb

volumes:
  mongodb_data: