name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root123
          MONGO_INITDB_DATABASE: invoiceapp

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies and run tests (Invoice App)
        working-directory: ./invoiceapp
        run: |
          npm ci
          npm test

      - name: Install dependencies and run tests (Email Sender)
        working-directory: ./email-sender
        run: |
          npm ci
          npm test

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: |
            invoiceapp/coverage
            email-sender/coverage

      - name: Run e2e tests
        run: npm run test:e2e
        working-directory: ./invoiceapp
        env:
          MONGODB_URI: mongodb://root:root123@localhost:27017/invoiceapp 